//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoInfoRefCancelacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoInfoRefCancelacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numAprobacion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="idTransaccionAutorizador" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoInfoRefCancelacion", propOrder = {
    "numAprobacion",
    "idTransaccionAutorizador"
})
public class TipoInfoRefCancelacion {

    protected int numAprobacion;
    protected long idTransaccionAutorizador;

    /**
     * Gets the value of the numAprobacion property.
     * 
     */
    public int getNumAprobacion() {
        return numAprobacion;
    }

    /**
     * Sets the value of the numAprobacion property.
     * 
     */
    public void setNumAprobacion(int value) {
        this.numAprobacion = value;
    }

    /**
     * Gets the value of the idTransaccionAutorizador property.
     * 
     */
    public long getIdTransaccionAutorizador() {
        return idTransaccionAutorizador;
    }

    /**
     * Sets the value of the idTransaccionAutorizador property.
     * 
     */
    public void setIdTransaccionAutorizador(long value) {
        this.idTransaccionAutorizador = value;
    }

}
