//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb.globalpay;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="consultarEstadoMultiCompraFault" type="{http://www.rbm.com.co/esb/globalpay/}FaultInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "consultarEstadoMultiCompraFault"
})
@XmlRootElement(name = "ConsultarEstadoMultiCompraFault")
public class ConsultarEstadoMultiCompraFault {

    @XmlElement(required = true)
    protected FaultInfo consultarEstadoMultiCompraFault;

    /**
     * Gets the value of the consultarEstadoMultiCompraFault property.
     * 
     * @return
     *     possible object is
     *     {@link FaultInfo }
     *     
     */
    public FaultInfo getConsultarEstadoMultiCompraFault() {
        return consultarEstadoMultiCompraFault;
    }

    /**
     * Sets the value of the consultarEstadoMultiCompraFault property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultInfo }
     *     
     */
    public void setConsultarEstadoMultiCompraFault(FaultInfo value) {
        this.consultarEstadoMultiCompraFault = value;
    }

}
