//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb.globalpay;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="credenciales" type="{http://www.rbm.com.co/esb/globalpay/}TipoCredenciales" minOccurs="0"/>
 *         &lt;element name="cabeceraSolicitud" type="{http://www.rbm.com.co/esb/globalpay/}TipoCabeceraSolicitud"/>
 *         &lt;element name="idTransaccion" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="22"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "credenciales",
    "cabeceraSolicitud",
    "idTransaccion"
})
@XmlRootElement(name = "ConsultarEstadoMultiCompraSolicitud")
public class ConsultarEstadoMultiCompraSolicitud {

    protected TipoCredenciales credenciales;
    @XmlElement(required = true)
    protected TipoCabeceraSolicitud cabeceraSolicitud;
    protected String idTransaccion;

    /**
     * Gets the value of the credenciales property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCredenciales }
     *     
     */
    public TipoCredenciales getCredenciales() {
        return credenciales;
    }

    /**
     * Sets the value of the credenciales property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCredenciales }
     *     
     */
    public void setCredenciales(TipoCredenciales value) {
        this.credenciales = value;
    }

    /**
     * Gets the value of the cabeceraSolicitud property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCabeceraSolicitud }
     *     
     */
    public TipoCabeceraSolicitud getCabeceraSolicitud() {
        return cabeceraSolicitud;
    }

    /**
     * Sets the value of the cabeceraSolicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCabeceraSolicitud }
     *     
     */
    public void setCabeceraSolicitud(TipoCabeceraSolicitud value) {
        this.cabeceraSolicitud = value;
    }

    /**
     * Gets the value of the idTransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdTransaccion() {
        return idTransaccion;
    }

    /**
     * Sets the value of the idTransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdTransaccion(String value) {
        this.idTransaccion = value;
    }

}
