//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb.globalpay;

import javax.xml.ws.WebFault;

@WebFault(name = "IniciarTransaccionDeCompraFault", targetNamespace = "http://www.rbm.com.co/esb/globalpay/")
public class IniciarTransaccionDeCompraFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IniciarTransaccionDeCompraFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IniciarTransaccionDeCompraFaultException(String message, IniciarTransaccionDeCompraFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IniciarTransaccionDeCompraFaultException(String message, IniciarTransaccionDeCompraFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: co.com.rbm.esb.globalpay.IniciarTransaccionDeCompraFault
     */
    public IniciarTransaccionDeCompraFault getFaultInfo() {
        return faultInfo;
    }

}
