//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb.globalpay;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="credenciales" type="{http://www.rbm.com.co/esb/globalpay/}TipoCredenciales" minOccurs="0"/>
 *         &lt;element name="cabeceraSolicitud" type="{http://www.rbm.com.co/esb/globalpay/}TipoCabeceraSolicitud"/>
 *         &lt;element name="infoPersona" type="{http://www.rbm.com.co/esb/globalpay/}TipoInfoPersona" minOccurs="0"/>
 *         &lt;element name="informacionComercio" type="{http://www.rbm.com.co/esb/globalpay/}TipoInformacionComercio" minOccurs="0"/>
 *         &lt;element name="infoCompra" type="{http://www.rbm.com.co/esb/globalpay/}TipoInfoCompra"/>
 *         &lt;element name="infoSolicitudPSE" type="{http://www.rbm.com.co/esb/globalpay/}TipoInfoSolicitudPSE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "credenciales",
    "cabeceraSolicitud",
    "infoPersona",
    "informacionComercio",
    "infoCompra",
    "infoSolicitudPSE"
})
@XmlRootElement(name = "IniciarTransaccionDeCompraSolicitud")
public class IniciarTransaccionDeCompraSolicitud {

    protected TipoCredenciales credenciales;
    @XmlElement(required = true)
    protected TipoCabeceraSolicitud cabeceraSolicitud;
    protected TipoInfoPersona infoPersona;
    protected TipoInformacionComercio informacionComercio;
    @XmlElement(required = true)
    protected TipoInfoCompra infoCompra;
    protected TipoInfoSolicitudPSE infoSolicitudPSE;

    /**
     * Gets the value of the credenciales property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCredenciales }
     *     
     */
    public TipoCredenciales getCredenciales() {
        return credenciales;
    }

    /**
     * Sets the value of the credenciales property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCredenciales }
     *     
     */
    public void setCredenciales(TipoCredenciales value) {
        this.credenciales = value;
    }

    /**
     * Gets the value of the cabeceraSolicitud property.
     * 
     * @return
     *     possible object is
     *     {@link TipoCabeceraSolicitud }
     *     
     */
    public TipoCabeceraSolicitud getCabeceraSolicitud() {
        return cabeceraSolicitud;
    }

    /**
     * Sets the value of the cabeceraSolicitud property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoCabeceraSolicitud }
     *     
     */
    public void setCabeceraSolicitud(TipoCabeceraSolicitud value) {
        this.cabeceraSolicitud = value;
    }

    /**
     * Gets the value of the infoPersona property.
     * 
     * @return
     *     possible object is
     *     {@link TipoInfoPersona }
     *     
     */
    public TipoInfoPersona getInfoPersona() {
        return infoPersona;
    }

    /**
     * Sets the value of the infoPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoInfoPersona }
     *     
     */
    public void setInfoPersona(TipoInfoPersona value) {
        this.infoPersona = value;
    }

    /**
     * Gets the value of the informacionComercio property.
     * 
     * @return
     *     possible object is
     *     {@link TipoInformacionComercio }
     *     
     */
    public TipoInformacionComercio getInformacionComercio() {
        return informacionComercio;
    }

    /**
     * Sets the value of the informacionComercio property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoInformacionComercio }
     *     
     */
    public void setInformacionComercio(TipoInformacionComercio value) {
        this.informacionComercio = value;
    }

    /**
     * Gets the value of the infoCompra property.
     * 
     * @return
     *     possible object is
     *     {@link TipoInfoCompra }
     *     
     */
    public TipoInfoCompra getInfoCompra() {
        return infoCompra;
    }

    /**
     * Sets the value of the infoCompra property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoInfoCompra }
     *     
     */
    public void setInfoCompra(TipoInfoCompra value) {
        this.infoCompra = value;
    }

    /**
     * Gets the value of the infoSolicitudPSE property.
     * 
     * @return
     *     possible object is
     *     {@link TipoInfoSolicitudPSE }
     *     
     */
    public TipoInfoSolicitudPSE getInfoSolicitudPSE() {
        return infoSolicitudPSE;
    }

    /**
     * Sets the value of the infoSolicitudPSE property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoInfoSolicitudPSE }
     *     
     */
    public void setInfoSolicitudPSE(TipoInfoSolicitudPSE value) {
        this.infoSolicitudPSE = value;
    }

}
