//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb.globalpay;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.com.rbm.esb.globalpay package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.com.rbm.esb.globalpay
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultarEstadoDePagoFault }
     * 
     */
    public ConsultarEstadoDePagoFault createConsultarEstadoDePagoFault() {
        return new ConsultarEstadoDePagoFault();
    }

    /**
     * Create an instance of {@link FaultInfo }
     * 
     */
    public FaultInfo createFaultInfo() {
        return new FaultInfo();
    }

    /**
     * Create an instance of {@link ConsultarEstadoDePagoRespuesta }
     * 
     */
    public ConsultarEstadoDePagoRespuesta createConsultarEstadoDePagoRespuesta() {
        return new ConsultarEstadoDePagoRespuesta();
    }

    /**
     * Create an instance of {@link TipoCabeceraSolicitud }
     * 
     */
    public TipoCabeceraSolicitud createTipoCabeceraSolicitud() {
        return new TipoCabeceraSolicitud();
    }

    /**
     * Create an instance of {@link TipoInfoPago }
     * 
     */
    public TipoInfoPago createTipoInfoPago() {
        return new TipoInfoPago();
    }

    /**
     * Create an instance of {@link TipoInfoPSE }
     * 
     */
    public TipoInfoPSE createTipoInfoPSE() {
        return new TipoInfoPSE();
    }

    /**
     * Create an instance of {@link ConsultarEstadoMultiCompraRespuesta }
     * 
     */
    public ConsultarEstadoMultiCompraRespuesta createConsultarEstadoMultiCompraRespuesta() {
        return new ConsultarEstadoMultiCompraRespuesta();
    }

    /**
     * Create an instance of {@link TipoInfoDispersionPago }
     * 
     */
    public TipoInfoDispersionPago createTipoInfoDispersionPago() {
        return new TipoInfoDispersionPago();
    }

    /**
     * Create an instance of {@link ConsultarEstadoMultiCompraFault }
     * 
     */
    public ConsultarEstadoMultiCompraFault createConsultarEstadoMultiCompraFault() {
        return new ConsultarEstadoMultiCompraFault();
    }

    /**
     * Create an instance of {@link IniciarTransaccionMultiCompraFault }
     * 
     */
    public IniciarTransaccionMultiCompraFault createIniciarTransaccionMultiCompraFault() {
        return new IniciarTransaccionMultiCompraFault();
    }

    /**
     * Create an instance of {@link IniciarTransaccionDeCompraFault }
     * 
     */
    public IniciarTransaccionDeCompraFault createIniciarTransaccionDeCompraFault() {
        return new IniciarTransaccionDeCompraFault();
    }

    /**
     * Create an instance of {@link IniciarTransaccionDeCompraSolicitud }
     * 
     */
    public IniciarTransaccionDeCompraSolicitud createIniciarTransaccionDeCompraSolicitud() {
        return new IniciarTransaccionDeCompraSolicitud();
    }

    /**
     * Create an instance of {@link TipoCredenciales }
     * 
     */
    public TipoCredenciales createTipoCredenciales() {
        return new TipoCredenciales();
    }

    /**
     * Create an instance of {@link TipoInfoPersona }
     * 
     */
    public TipoInfoPersona createTipoInfoPersona() {
        return new TipoInfoPersona();
    }

    /**
     * Create an instance of {@link TipoInformacionComercio }
     * 
     */
    public TipoInformacionComercio createTipoInformacionComercio() {
        return new TipoInformacionComercio();
    }

    /**
     * Create an instance of {@link TipoInfoCompra }
     * 
     */
    public TipoInfoCompra createTipoInfoCompra() {
        return new TipoInfoCompra();
    }

    /**
     * Create an instance of {@link TipoInfoSolicitudPSE }
     * 
     */
    public TipoInfoSolicitudPSE createTipoInfoSolicitudPSE() {
        return new TipoInfoSolicitudPSE();
    }

    /**
     * Create an instance of {@link IniciarTransaccionDeCompraRespuesta }
     * 
     */
    public IniciarTransaccionDeCompraRespuesta createIniciarTransaccionDeCompraRespuesta() {
        return new IniciarTransaccionDeCompraRespuesta();
    }

    /**
     * Create an instance of {@link TipoInfoTransaccionResp }
     * 
     */
    public TipoInfoTransaccionResp createTipoInfoTransaccionResp() {
        return new TipoInfoTransaccionResp();
    }

    /**
     * Create an instance of {@link ConsultarEstadoDePagoSolicitud }
     * 
     */
    public ConsultarEstadoDePagoSolicitud createConsultarEstadoDePagoSolicitud() {
        return new ConsultarEstadoDePagoSolicitud();
    }

    /**
     * Create an instance of {@link IniciarTransaccionMultiCompraSolicitud }
     * 
     */
    public IniciarTransaccionMultiCompraSolicitud createIniciarTransaccionMultiCompraSolicitud() {
        return new IniciarTransaccionMultiCompraSolicitud();
    }

    /**
     * Create an instance of {@link TipoInfoDispersionCompra }
     * 
     */
    public TipoInfoDispersionCompra createTipoInfoDispersionCompra() {
        return new TipoInfoDispersionCompra();
    }

    /**
     * Create an instance of {@link IniciarTransaccionMultiCompraRepuesta }
     * 
     */
    public IniciarTransaccionMultiCompraRepuesta createIniciarTransaccionMultiCompraRepuesta() {
        return new IniciarTransaccionMultiCompraRepuesta();
    }

    /**
     * Create an instance of {@link ConsultarEstadoMultiCompraSolicitud }
     * 
     */
    public ConsultarEstadoMultiCompraSolicitud createConsultarEstadoMultiCompraSolicitud() {
        return new ConsultarEstadoMultiCompraSolicitud();
    }

    /**
     * Create an instance of {@link TipoInfoPuntoInteraccion }
     * 
     */
    public TipoInfoPuntoInteraccion createTipoInfoPuntoInteraccion() {
        return new TipoInfoPuntoInteraccion();
    }

    /**
     * Create an instance of {@link TipoInfoAtencionCliente }
     * 
     */
    public TipoInfoAtencionCliente createTipoInfoAtencionCliente() {
        return new TipoInfoAtencionCliente();
    }

    /**
     * Create an instance of {@link TipoInfoComercio }
     * 
     */
    public TipoInfoComercio createTipoInfoComercio() {
        return new TipoInfoComercio();
    }

}
