//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.rbm.com.co/esb/globalpay/")
package co.com.rbm.esb.globalpay;
