//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb.globalpay;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoEstadoActualTransaccion.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipoEstadoActualTransaccion">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Iniciado"/>
 *     &lt;enumeration value="Aprobado"/>
 *     &lt;enumeration value="Rechazado"/>
 *     &lt;enumeration value="Procesando"/>
 *     &lt;enumeration value="Error"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipoEstadoActualTransaccion")
@XmlEnum
public enum TipoEstadoActualTransaccion {

    @XmlEnumValue("Iniciado")
    INICIADO("Iniciado"),
    @XmlEnumValue("Aprobado")
    APROBADO("Aprobado"),
    @XmlEnumValue("Rechazado")
    RECHAZADO("Rechazado"),
    @XmlEnumValue("Procesando")
    PROCESANDO("Procesando"),
    @XmlEnumValue("Error")
    ERROR("Error");
    private final String value;

    TipoEstadoActualTransaccion(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipoEstadoActualTransaccion fromValue(String v) {
        for (TipoEstadoActualTransaccion c: TipoEstadoActualTransaccion.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
