//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb.globalpay;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoInfoAtencionCliente complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoInfoAtencionCliente">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="direccionContacto" type="{http://www.rbm.com.co/esb/globalpay/}TipoDireccion" minOccurs="0"/>
 *         &lt;element name="telefonoContacto" type="{http://www.rbm.com.co/esb/globalpay/}TipoTelefono" minOccurs="0"/>
 *         &lt;element name="correoElectronicoContacto" type="{http://www.rbm.com.co/esb/globalpay/}TipoCorreoElectronico" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoInfoAtencionCliente", propOrder = {
    "direccionContacto",
    "telefonoContacto",
    "correoElectronicoContacto"
})
public class TipoInfoAtencionCliente {

    protected String direccionContacto;
    protected Long telefonoContacto;
    protected String correoElectronicoContacto;

    /**
     * Gets the value of the direccionContacto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccionContacto() {
        return direccionContacto;
    }

    /**
     * Sets the value of the direccionContacto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccionContacto(String value) {
        this.direccionContacto = value;
    }

    /**
     * Gets the value of the telefonoContacto property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTelefonoContacto() {
        return telefonoContacto;
    }

    /**
     * Sets the value of the telefonoContacto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTelefonoContacto(Long value) {
        this.telefonoContacto = value;
    }

    /**
     * Gets the value of the correoElectronicoContacto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorreoElectronicoContacto() {
        return correoElectronicoContacto;
    }

    /**
     * Sets the value of the correoElectronicoContacto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorreoElectronicoContacto(String value) {
        this.correoElectronicoContacto = value;
    }

}
