//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb.globalpay;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import co.com.rbm.esb.TipoInfoImpuestos;
import co.com.rbm.esb.TipoMontoDetallado;


/**
 * <p>Java class for TipoInfoCompra complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoInfoCompra">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroFactura">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="montoTotal">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minExclusive value="0"/>
 *               &lt;maxExclusive value="999999999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="infoImpuestos" type="{http://www.rbm.com.co/esb/}TipoInfoImpuestos" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="montoDetallado" type="{http://www.rbm.com.co/esb/}TipoMontoDetallado" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="infoComercio" type="{http://www.rbm.com.co/esb/globalpay/}TipoInfoComercio" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoInfoCompra", propOrder = {
    "numeroFactura",
    "montoTotal",
    "infoImpuestos",
    "montoDetallado",
    "infoComercio"
})
public class TipoInfoCompra {

    @XmlElement(required = true)
    protected String numeroFactura;
    @XmlElement(required = true)
    protected BigDecimal montoTotal;
    @XmlElement(nillable = true)
    protected List<TipoInfoImpuestos> infoImpuestos;
    @XmlElement(nillable = true)
    protected List<TipoMontoDetallado> montoDetallado;
    protected TipoInfoComercio infoComercio;

    /**
     * Gets the value of the numeroFactura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroFactura() {
        return numeroFactura;
    }

    /**
     * Sets the value of the numeroFactura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroFactura(String value) {
        this.numeroFactura = value;
    }

    /**
     * Gets the value of the montoTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMontoTotal() {
        return montoTotal;
    }

    /**
     * Sets the value of the montoTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMontoTotal(BigDecimal value) {
        this.montoTotal = value;
    }

    /**
     * Gets the value of the infoImpuestos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infoImpuestos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfoImpuestos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoInfoImpuestos }
     * 
     * 
     */
    public List<TipoInfoImpuestos> getInfoImpuestos() {
        if (infoImpuestos == null) {
            infoImpuestos = new ArrayList<TipoInfoImpuestos>();
        }
        return this.infoImpuestos;
    }

    /**
     * Gets the value of the montoDetallado property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the montoDetallado property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMontoDetallado().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoMontoDetallado }
     * 
     * 
     */
    public List<TipoMontoDetallado> getMontoDetallado() {
        if (montoDetallado == null) {
            montoDetallado = new ArrayList<TipoMontoDetallado>();
        }
        return this.montoDetallado;
    }

    /**
     * Gets the value of the infoComercio property.
     * 
     * @return
     *     possible object is
     *     {@link TipoInfoComercio }
     *     
     */
    public TipoInfoComercio getInfoComercio() {
        return infoComercio;
    }

    /**
     * Sets the value of the infoComercio property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoInfoComercio }
     *     
     */
    public void setInfoComercio(TipoInfoComercio value) {
        this.infoComercio = value;
    }

}
