//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb.globalpay;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TipoInfoPSE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoInfoPSE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codTrazabilidad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="referencia" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fechaTransaccion" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="fechaProcBanco" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="cicloTransaccion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nitAdquiriente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="descripcionBanco" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoInfoPSE", propOrder = {
    "codTrazabilidad",
    "referencia",
    "fechaTransaccion",
    "fechaProcBanco",
    "cicloTransaccion",
    "nitAdquiriente",
    "descripcionBanco"
})
public class TipoInfoPSE {

    protected String codTrazabilidad;
    protected int referencia;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaTransaccion;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaProcBanco;
    protected String cicloTransaccion;
    protected String nitAdquiriente;
    protected String descripcionBanco;

    /**
     * Gets the value of the codTrazabilidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodTrazabilidad() {
        return codTrazabilidad;
    }

    /**
     * Sets the value of the codTrazabilidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodTrazabilidad(String value) {
        this.codTrazabilidad = value;
    }

    /**
     * Gets the value of the referencia property.
     * 
     */
    public int getReferencia() {
        return referencia;
    }

    /**
     * Sets the value of the referencia property.
     * 
     */
    public void setReferencia(int value) {
        this.referencia = value;
    }

    /**
     * Gets the value of the fechaTransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaTransaccion() {
        return fechaTransaccion;
    }

    /**
     * Sets the value of the fechaTransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaTransaccion(XMLGregorianCalendar value) {
        this.fechaTransaccion = value;
    }

    /**
     * Gets the value of the fechaProcBanco property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaProcBanco() {
        return fechaProcBanco;
    }

    /**
     * Sets the value of the fechaProcBanco property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaProcBanco(XMLGregorianCalendar value) {
        this.fechaProcBanco = value;
    }

    /**
     * Gets the value of the cicloTransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCicloTransaccion() {
        return cicloTransaccion;
    }

    /**
     * Sets the value of the cicloTransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCicloTransaccion(String value) {
        this.cicloTransaccion = value;
    }

    /**
     * Gets the value of the nitAdquiriente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNitAdquiriente() {
        return nitAdquiriente;
    }

    /**
     * Sets the value of the nitAdquiriente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNitAdquiriente(String value) {
        this.nitAdquiriente = value;
    }

    /**
     * Gets the value of the descripcionBanco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionBanco() {
        return descripcionBanco;
    }

    /**
     * Sets the value of the descripcionBanco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionBanco(String value) {
        this.descripcionBanco = value;
    }

}
