//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb.globalpay;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoInformacionComercio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoInformacionComercio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="politicaEntrega" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="politicaDevoluciones" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="serviciosOfrecidos" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="infoAtencionCliente" type="{http://www.rbm.com.co/esb/globalpay/}TipoInfoAtencionCliente" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoInformacionComercio", propOrder = {
    "politicaEntrega",
    "politicaDevoluciones",
    "serviciosOfrecidos",
    "infoAtencionCliente"
})
public class TipoInformacionComercio {

    protected String politicaEntrega;
    protected String politicaDevoluciones;
    protected String serviciosOfrecidos;
    protected TipoInfoAtencionCliente infoAtencionCliente;

    /**
     * Gets the value of the politicaEntrega property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoliticaEntrega() {
        return politicaEntrega;
    }

    /**
     * Sets the value of the politicaEntrega property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoliticaEntrega(String value) {
        this.politicaEntrega = value;
    }

    /**
     * Gets the value of the politicaDevoluciones property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoliticaDevoluciones() {
        return politicaDevoluciones;
    }

    /**
     * Sets the value of the politicaDevoluciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoliticaDevoluciones(String value) {
        this.politicaDevoluciones = value;
    }

    /**
     * Gets the value of the serviciosOfrecidos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiciosOfrecidos() {
        return serviciosOfrecidos;
    }

    /**
     * Sets the value of the serviciosOfrecidos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiciosOfrecidos(String value) {
        this.serviciosOfrecidos = value;
    }

    /**
     * Gets the value of the infoAtencionCliente property.
     * 
     * @return
     *     possible object is
     *     {@link TipoInfoAtencionCliente }
     *     
     */
    public TipoInfoAtencionCliente getInfoAtencionCliente() {
        return infoAtencionCliente;
    }

    /**
     * Sets the value of the infoAtencionCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoInfoAtencionCliente }
     *     
     */
    public void setInfoAtencionCliente(TipoInfoAtencionCliente value) {
        this.infoAtencionCliente = value;
    }

}
