//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-03/09/2011 06:46 PM(foreman)-)
//


package co.com.rbm.esb.globalpay;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoTipoMedioDePago.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipoTipoMedioDePago">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Credito"/>
 *     &lt;enumeration value="Debito"/>
 *     &lt;enumeration value="CreditoPrivado"/>
 *     &lt;enumeration value="DebitoPrivado"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipoTipoMedioDePago")
@XmlEnum
public enum TipoTipoMedioDePago {

    @XmlEnumValue("Credito")
    CREDITO("Credito"),
    @XmlEnumValue("Debito")
    DEBITO("Debito"),
    @XmlEnumValue("CreditoPrivado")
    CREDITO_PRIVADO("CreditoPrivado"),
    @XmlEnumValue("DebitoPrivado")
    DEBITO_PRIVADO("DebitoPrivado");
    private final String value;

    TipoTipoMedioDePago(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipoTipoMedioDePago fromValue(String v) {
        for (TipoTipoMedioDePago c: TipoTipoMedioDePago.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
