//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package co.com.rbm.esb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CabeceraType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CabeceraType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoTransaccion" type="{http://www.rbm.com.co/esb/}TipoTransaccion"/>
 *         &lt;element name="idTerminal" type="{http://www.rbm.com.co/esb/}IdTerminal"/>
 *         &lt;element name="idTransaccionTerminal" type="{http://www.rbm.com.co/esb/}IdTransaccionTerminal"/>
 *         &lt;element name="fechaTransaccion" type="{http://www.rbm.com.co/esb/}FechaTransaccion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CabeceraType", propOrder = {
    "tipoTransaccion",
    "idTerminal",
    "idTransaccionTerminal",
    "fechaTransaccion"
})
public class CabeceraType {

    @XmlElement(required = true)
    protected String tipoTransaccion;
    @XmlElement(required = true)
    protected String idTerminal;
    protected long idTransaccionTerminal;
    @XmlElement(required = true)
    protected XMLGregorianCalendar fechaTransaccion;

    /**
     * Gets the value of the tipoTransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoTransaccion() {
        return tipoTransaccion;
    }

    /**
     * Sets the value of the tipoTransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoTransaccion(String value) {
        this.tipoTransaccion = value;
    }

    /**
     * Gets the value of the idTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdTerminal() {
        return idTerminal;
    }

    /**
     * Sets the value of the idTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdTerminal(String value) {
        this.idTerminal = value;
    }

    /**
     * Gets the value of the idTransaccionTerminal property.
     * 
     */
    public long getIdTransaccionTerminal() {
        return idTransaccionTerminal;
    }

    /**
     * Sets the value of the idTransaccionTerminal property.
     * 
     */
    public void setIdTransaccionTerminal(long value) {
        this.idTransaccionTerminal = value;
    }

    /**
     * Gets the value of the fechaTransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaTransaccion() {
        return fechaTransaccion;
    }

    /**
     * Sets the value of the fechaTransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaTransaccion(XMLGregorianCalendar value) {
        this.fechaTransaccion = value;
    }

}
