//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.rbm.com.co/esb/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package co.com.rbm.esb;
