//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package co.com.rbm.esb.comercio.compra;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "CompraElectronica_HTTP_Service", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", wsdlLocation = "META-INF/wsdl/CompraElectronicaService.wsdl")
public class CompraElectronicaHTTPService
    extends Service
{

    private final static URL COMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPRAELECTRONICAHTTPSERVICE_EXCEPTION;
    private final static QName COMPRAELECTRONICAHTTPSERVICE_QNAME = new QName("http://www.rbm.com.co/esb/comercio/compra/", "CompraElectronica_HTTP_Service");

    static {
            COMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION = co.com.rbm.esb.comercio.compra.CompraElectronicaHTTPService.class.getResource("/META-INF/wsdl/CompraElectronicaService.wsdl");
        WebServiceException e = null;
        if (COMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/CompraElectronicaService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        COMPRAELECTRONICAHTTPSERVICE_EXCEPTION = e;
    }

    public CompraElectronicaHTTPService() {
        super(__getWsdlLocation(), COMPRAELECTRONICAHTTPSERVICE_QNAME);
    }

    public CompraElectronicaHTTPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPRAELECTRONICAHTTPSERVICE_QNAME, features);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation) {
        super(wsdlLocation, COMPRAELECTRONICAHTTPSERVICE_QNAME);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPRAELECTRONICAHTTPSERVICE_QNAME, features);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompraElectronicaHTTPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CompraElectronicaMsgSetPortType
     */
    @WebEndpoint(name = "CompraElectronica_HTTP_Port")
    public CompraElectronicaMsgSetPortType getCompraElectronicaHTTPPort() {
        return super.getPort(new QName("http://www.rbm.com.co/esb/comercio/compra/", "CompraElectronica_HTTP_Port"), CompraElectronicaMsgSetPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompraElectronicaMsgSetPortType
     */
    @WebEndpoint(name = "CompraElectronica_HTTP_Port")
    public CompraElectronicaMsgSetPortType getCompraElectronicaHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.rbm.com.co/esb/comercio/compra/", "CompraElectronica_HTTP_Port"), CompraElectronicaMsgSetPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPRAELECTRONICAHTTPSERVICE_EXCEPTION!= null) {
            throw COMPRAELECTRONICAHTTPSERVICE_EXCEPTION;
        }
        return COMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION;
    }

}
