//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package co.com.rbm.esb.comercio.compra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "CompraElectronica_MsgSetPortType", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    co.com.rbm.esb.ObjectFactory.class,
    co.com.rbm.esb.comercio.ObjectFactory.class,
    co.com.rbm.esb.comercio.compra.ObjectFactory.class
})
public interface CompraElectronicaMsgSetPortType {


    /**
     * 
     * @param compraProcesarSolicitud
     * @return
     *     returns co.com.rbm.esb.comercio.compra.TipoRespuesta
     */
    @WebMethod
    @WebResult(name = "compraProcesarRespuesta", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraProcesarRespuesta")
    public TipoRespuesta compraProcesar(
        @WebParam(name = "compraProcesarSolicitud", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraProcesarSolicitud")
        TipoSolicitudCompra compraProcesarSolicitud);

    /**
     * 
     * @param compraReversarSolicitud
     * @return
     *     returns co.com.rbm.esb.comercio.compra.TipoRespuesta
     */
    @WebMethod
    @WebResult(name = "compraReversarRespuesta", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraReversarRespuesta")
    public TipoRespuesta compraReversar(
        @WebParam(name = "compraReversarSolicitud", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraReversarSolicitud")
        TipoSolicitudCompra compraReversarSolicitud);

}
