//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.rbm.esb.comercio;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.rbm.esb.TipoInfoUbicacion;


/**
 * <p>Java class for TipoInfoTerminal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoInfoTerminal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nombreAdquiriente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="infoUbicacion" type="{http://www.rbm.com.co/esb/}TipoInfoUbicacion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoInfoTerminal", propOrder = {
    "nombreAdquiriente",
    "infoUbicacion"
})
public class TipoInfoTerminal {

    @XmlElement(required = true)
    protected String nombreAdquiriente;
    @XmlElement(required = true)
    protected TipoInfoUbicacion infoUbicacion;

    /**
     * Gets the value of the nombreAdquiriente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreAdquiriente() {
        return nombreAdquiriente;
    }

    /**
     * Sets the value of the nombreAdquiriente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreAdquiriente(String value) {
        this.nombreAdquiriente = value;
    }

    /**
     * Gets the value of the infoUbicacion property.
     * 
     * @return
     *     possible object is
     *     {@link TipoInfoUbicacion }
     *     
     */
    public TipoInfoUbicacion getInfoUbicacion() {
        return infoUbicacion;
    }

    /**
     * Sets the value of the infoUbicacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoInfoUbicacion }
     *     
     */
    public void setInfoUbicacion(TipoInfoUbicacion value) {
        this.infoUbicacion = value;
    }

}
