//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package co.com.rbm.esb.gestionarnovedades;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CampoAct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CampoAct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoTag" type="{http://www.rbm.com.co/esb/gestionarNovedades}TipoTag"/>
 *         &lt;element name="data" type="{http://www.rbm.com.co/esb/gestionarNovedades}Data"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CampoAct", propOrder = {
    "tipoTag",
    "data"
})
public class CampoAct {

    @XmlElement(required = true)
    protected String tipoTag;
    @XmlElement(required = true)
    protected String data;

    /**
     * Gets the value of the tipoTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoTag() {
        return tipoTag;
    }

    /**
     * Sets the value of the tipoTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoTag(String value) {
        this.tipoTag = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

}
