//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package co.com.rbm.esb.gestionarnovedades;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "gestionarNovedadesPortType", targetNamespace = "http://www.rbm.com.co/esb/gestionarNovedades")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    co.com.rbm.esb.ObjectFactory.class,
    co.com.rbm.esb.gestionarnovedades.ObjectFactory.class
})
public interface GestionarNovedadesPortType {


    /**
     * 
     * @param gestionarNovedadesSolicitud
     * @return
     *     returns co.com.rbm.esb.gestionarnovedades.GestionarNovedadesRespuestaResType
     */
    @WebMethod(action = "http://www.rbm.com.co/esb/gestionarNovedades")
    @WebResult(name = "gestionarNovedadesRespuesta", targetNamespace = "http://www.rbm.com.co/esb/gestionarNovedades", partName = "gestionarNovedadesRespuesta")
    public GestionarNovedadesRespuestaResType gestionarNovedadesProcesar(
        @WebParam(name = "gestionarNovedadesSolicitud", targetNamespace = "http://www.rbm.com.co/esb/gestionarNovedades", partName = "gestionarNovedadesSolicitud")
        GestionarNovedadesSolicitudReqType gestionarNovedadesSolicitud);

}
