//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package co.com.rbm.esb.gestionarnovedades;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "gestionarNovedades_HTTP_Service", targetNamespace = "http://www.rbm.com.co/esb/gestionarNovedades", wsdlLocation = "META-INF/wsdl/gestionarNovedades.wsdl")
public class GestionarNovedadesHTTPService
    extends Service
{

    private final static URL GESTIONARNOVEDADESHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONARNOVEDADESHTTPSERVICE_EXCEPTION;
    private final static QName GESTIONARNOVEDADESHTTPSERVICE_QNAME = new QName("http://www.rbm.com.co/esb/gestionarNovedades", "gestionarNovedades_HTTP_Service");

    static {
            GESTIONARNOVEDADESHTTPSERVICE_WSDL_LOCATION = co.com.rbm.esb.gestionarnovedades.GestionarNovedadesHTTPService.class.getResource("/META-INF/wsdl/gestionarNovedades.wsdl");
        WebServiceException e = null;
        if (GESTIONARNOVEDADESHTTPSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/gestionarNovedades.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GESTIONARNOVEDADESHTTPSERVICE_EXCEPTION = e;
    }

    public GestionarNovedadesHTTPService() {
        super(__getWsdlLocation(), GESTIONARNOVEDADESHTTPSERVICE_QNAME);
    }

    public GestionarNovedadesHTTPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONARNOVEDADESHTTPSERVICE_QNAME, features);
    }

    public GestionarNovedadesHTTPService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONARNOVEDADESHTTPSERVICE_QNAME);
    }

    public GestionarNovedadesHTTPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONARNOVEDADESHTTPSERVICE_QNAME, features);
    }

    public GestionarNovedadesHTTPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionarNovedadesHTTPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GestionarNovedadesPortType
     */
    @WebEndpoint(name = "gestionarNovedades_HTTP_Port")
    public GestionarNovedadesPortType getGestionarNovedadesHTTPPort() {
        return super.getPort(new QName("http://www.rbm.com.co/esb/gestionarNovedades", "gestionarNovedades_HTTP_Port"), GestionarNovedadesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionarNovedadesPortType
     */
    @WebEndpoint(name = "gestionarNovedades_HTTP_Port")
    public GestionarNovedadesPortType getGestionarNovedadesHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.rbm.com.co/esb/gestionarNovedades", "gestionarNovedades_HTTP_Port"), GestionarNovedadesPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONARNOVEDADESHTTPSERVICE_EXCEPTION!= null) {
            throw GESTIONARNOVEDADESHTTPSERVICE_EXCEPTION;
        }
        return GESTIONARNOVEDADESHTTPSERVICE_WSDL_LOCATION;
    }

}
