//
// Generated By:JAX-WS RI IBM 2.2.1-11/30/2010 12:42 PM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package co.com.rbm.esb.gestionarnovedades;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.com.rbm.esb.gestionarnovedades package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GestionarNovedadesRespuesta_QNAME = new QName("http://www.rbm.com.co/esb/gestionarNovedades", "gestionarNovedadesRespuesta");
    private final static QName _GestionarNovedadesSolicitud_QNAME = new QName("http://www.rbm.com.co/esb/gestionarNovedades", "gestionarNovedadesSolicitud");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.com.rbm.esb.gestionarnovedades
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GestionarNovedadesSolicitudReqType }
     * 
     */
    public GestionarNovedadesSolicitudReqType createGestionarNovedadesSolicitudReqType() {
        return new GestionarNovedadesSolicitudReqType();
    }

    /**
     * Create an instance of {@link GestionarNovedadesRespuestaResType }
     * 
     */
    public GestionarNovedadesRespuestaResType createGestionarNovedadesRespuestaResType() {
        return new GestionarNovedadesRespuestaResType();
    }

    /**
     * Create an instance of {@link InfoTransaccionReqType }
     * 
     */
    public InfoTransaccionReqType createInfoTransaccionReqType() {
        return new InfoTransaccionReqType();
    }

    /**
     * Create an instance of {@link CampoAct }
     * 
     */
    public CampoAct createCampoAct() {
        return new CampoAct();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GestionarNovedadesRespuestaResType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/gestionarNovedades", name = "gestionarNovedadesRespuesta")
    public JAXBElement<GestionarNovedadesRespuestaResType> createGestionarNovedadesRespuesta(GestionarNovedadesRespuestaResType value) {
        return new JAXBElement<GestionarNovedadesRespuestaResType>(_GestionarNovedadesRespuesta_QNAME, GestionarNovedadesRespuestaResType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GestionarNovedadesSolicitudReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/gestionarNovedades", name = "gestionarNovedadesSolicitud")
    public JAXBElement<GestionarNovedadesSolicitudReqType> createGestionarNovedadesSolicitud(GestionarNovedadesSolicitudReqType value) {
        return new JAXBElement<GestionarNovedadesSolicitudReqType>(_GestionarNovedadesSolicitud_QNAME, GestionarNovedadesSolicitudReqType.class, null, value);
    }

}
