//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package co.com.rbm.esb.pignorarcuenta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for InfoTransaccionReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfoTransaccionReqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoRegistro" type="{http://www.rbm.com.co/esb/pignorarCuenta}TipoRegistroType"/>
 *         &lt;element name="Franquicia" type="{http://www.rbm.com.co/esb/pignorarCuenta}FranquiciaType"/>
 *         &lt;element name="CodigoUnico" type="{http://www.rbm.com.co/esb/pignorarCuenta}CodigoUnicoType"/>
 *         &lt;element name="Adquiriente" type="{http://www.rbm.com.co/esb/pignorarCuenta}AdquirienteType"/>
 *         &lt;element name="TipoCuenta" type="{http://www.rbm.com.co/esb/pignorarCuenta}TipoCuentaType"/>
 *         &lt;element name="Cuenta" type="{http://www.rbm.com.co/esb/pignorarCuenta}CuentaType"/>
 *         &lt;element name="FechaInicial" type="{http://www.rbm.com.co/esb/pignorarCuenta}FechaType"/>
 *         &lt;element name="FechaFinal" type="{http://www.rbm.com.co/esb/pignorarCuenta}FechaType"/>
 *         &lt;element name="Usuario" type="{http://www.rbm.com.co/esb/pignorarCuenta}UsuarioType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoTransaccionReqType", propOrder = {
    "tipoRegistro",
    "franquicia",
    "codigoUnico",
    "adquiriente",
    "tipoCuenta",
    "cuenta",
    "fechaInicial",
    "fechaFinal",
    "usuario"
})
public class InfoTransaccionReqType {

    @XmlElement(name = "TipoRegistro", required = true)
    protected String tipoRegistro;
    @XmlElement(name = "Franquicia", required = true)
    protected String franquicia;
    @XmlElement(name = "CodigoUnico", required = true)
    protected String codigoUnico;
    @XmlElement(name = "Adquiriente", required = true)
    protected String adquiriente;
    @XmlElement(name = "TipoCuenta", required = true)
    protected String tipoCuenta;
    @XmlElement(name = "Cuenta", required = true)
    protected String cuenta;
    @XmlElement(name = "FechaInicial", required = true)
    protected XMLGregorianCalendar fechaInicial;
    @XmlElement(name = "FechaFinal", required = true)
    protected XMLGregorianCalendar fechaFinal;
    @XmlElement(name = "Usuario", required = true)
    protected String usuario;

    /**
     * Gets the value of the tipoRegistro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoRegistro() {
        return tipoRegistro;
    }

    /**
     * Sets the value of the tipoRegistro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoRegistro(String value) {
        this.tipoRegistro = value;
    }

    /**
     * Gets the value of the franquicia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFranquicia() {
        return franquicia;
    }

    /**
     * Sets the value of the franquicia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFranquicia(String value) {
        this.franquicia = value;
    }

    /**
     * Gets the value of the codigoUnico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoUnico() {
        return codigoUnico;
    }

    /**
     * Sets the value of the codigoUnico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoUnico(String value) {
        this.codigoUnico = value;
    }

    /**
     * Gets the value of the adquiriente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdquiriente() {
        return adquiriente;
    }

    /**
     * Sets the value of the adquiriente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdquiriente(String value) {
        this.adquiriente = value;
    }

    /**
     * Gets the value of the tipoCuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoCuenta() {
        return tipoCuenta;
    }

    /**
     * Sets the value of the tipoCuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoCuenta(String value) {
        this.tipoCuenta = value;
    }

    /**
     * Gets the value of the cuenta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCuenta() {
        return cuenta;
    }

    /**
     * Sets the value of the cuenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCuenta(String value) {
        this.cuenta = value;
    }

    /**
     * Gets the value of the fechaInicial property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaInicial() {
        return fechaInicial;
    }

    /**
     * Sets the value of the fechaInicial property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaInicial(XMLGregorianCalendar value) {
        this.fechaInicial = value;
    }

    /**
     * Gets the value of the fechaFinal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaFinal() {
        return fechaFinal;
    }

    /**
     * Sets the value of the fechaFinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaFinal(XMLGregorianCalendar value) {
        this.fechaFinal = value;
    }

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsuario(String value) {
        this.usuario = value;
    }

}
