//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package co.com.rbm.esb.pignorarcuenta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "pignorarCuentaPortType", targetNamespace = "http://www.rbm.com.co/esb/pignorarCuenta")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    co.com.rbm.esbPignoracion.ObjectFactory.class,
    co.com.rbm.esb.pignorarcuenta.ObjectFactory.class
})
public interface PignorarCuentaPortType {


    /**
     * 
     * @param pignorarCuentaSolicitud
     * @return
     *     returns co.com.rbm.esb.pignorarcuenta.PignorarCuentaRespuestaResType
     */
    @WebMethod(action = "http://www.rbm.com.co/esb/pignorarCuenta")
    @WebResult(name = "pignorarCuentaRespuesta", targetNamespace = "http://www.rbm.com.co/esb/pignorarCuenta", partName = "pignorarCuentaRespuesta")
    public PignorarCuentaRespuestaResType pignorarCuentaProcesar(
        @WebParam(name = "pignorarCuentaSolicitud", targetNamespace = "http://www.rbm.com.co/esb/pignorarCuenta", partName = "pignorarCuentaSolicitud")
        PignorarCuentaSolicitudReqType pignorarCuentaSolicitud);

}
