//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package co.com.rbm.esb.comercio.compra.cancelacion;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "CompraElectronicaCancelacion_HTTP_Service", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", wsdlLocation = "META-INF/wsdl/CompraElectronicaCancelacionService.wsdl")
public class CompraElectronicaCancelacionHTTPService
    extends Service
{

    private final static URL COMPRAELECTRONICACANCELACIONHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPRAELECTRONICACANCELACIONHTTPSERVICE_EXCEPTION;
    private final static QName COMPRAELECTRONICACANCELACIONHTTPSERVICE_QNAME = new QName("http://www.rbm.com.co/esb/comercio/compra/", "CompraElectronicaCancelacion_HTTP_Service");

    static {
            COMPRAELECTRONICACANCELACIONHTTPSERVICE_WSDL_LOCATION = co.com.rbm.esb.comercio.compra.cancelacion.CompraElectronicaCancelacionHTTPService.class.getResource("/META-INF/wsdl/CompraElectronicaCancelacionService.wsdl");
        WebServiceException e = null;
        if (COMPRAELECTRONICACANCELACIONHTTPSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/CompraElectronicaCancelacionService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        COMPRAELECTRONICACANCELACIONHTTPSERVICE_EXCEPTION = e;
    }

    public CompraElectronicaCancelacionHTTPService() {
        super(__getWsdlLocation(), COMPRAELECTRONICACANCELACIONHTTPSERVICE_QNAME);
    }

    public CompraElectronicaCancelacionHTTPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPRAELECTRONICACANCELACIONHTTPSERVICE_QNAME, features);
    }

    public CompraElectronicaCancelacionHTTPService(URL wsdlLocation) {
        super(wsdlLocation, COMPRAELECTRONICACANCELACIONHTTPSERVICE_QNAME);
    }

    public CompraElectronicaCancelacionHTTPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPRAELECTRONICACANCELACIONHTTPSERVICE_QNAME, features);
    }

    public CompraElectronicaCancelacionHTTPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompraElectronicaCancelacionHTTPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CompraElectronicaMsgSetPortType
     */
    @WebEndpoint(name = "CompraElectronicaCancelacion_HTTP_Port")
    public CompraElectronicaMsgSetPortType getCompraElectronicaCancelacionHTTPPort() {
        return super.getPort(new QName("http://www.rbm.com.co/esb/comercio/compra/", "CompraElectronicaCancelacion_HTTP_Port"), CompraElectronicaMsgSetPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompraElectronicaMsgSetPortType
     */
    @WebEndpoint(name = "CompraElectronicaCancelacion_HTTP_Port")
    public CompraElectronicaMsgSetPortType getCompraElectronicaCancelacionHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.rbm.com.co/esb/comercio/compra/", "CompraElectronicaCancelacion_HTTP_Port"), CompraElectronicaMsgSetPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPRAELECTRONICACANCELACIONHTTPSERVICE_EXCEPTION!= null) {
            throw COMPRAELECTRONICACANCELACIONHTTPSERVICE_EXCEPTION;
        }
        return COMPRAELECTRONICACANCELACIONHTTPSERVICE_WSDL_LOCATION;
    }

}
