//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package co.com.rbm.esb.comercio.compra.cancelacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import co.com.rbm.esb.comercio.compra.TipoRespuesta;
import co.com.rbm.esb.comercio.compra.TipoSolicitudCancelacion;

@WebService(name = "CompraElectronica_MsgSetPortType", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    co.com.rbm.esb.ObjectFactory.class,
    co.com.rbm.esb.comercio.ObjectFactory.class,
    co.com.rbm.esb.comercio.compra.cancelacion.ObjectFactory.class
})
public interface CompraElectronicaMsgSetPortType {


    /**
     * 
     * @param compraCancelacionProcesarSolicitud
     * @return
     *     returns co.com.rbm.esb.comercio.compra.TipoRespuesta
     */
    @WebMethod
    @WebResult(name = "compraCancelacionProcesarRespuesta", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraCancelacionProcesarRespuesta")
    public TipoRespuesta compraCancelacionProcesar(
        @WebParam(name = "compraCancelacionProcesarSolicitud", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraCancelacionProcesarSolicitud")
        TipoSolicitudCancelacion compraCancelacionProcesarSolicitud);

    /**
     * 
     * @param compraCancelacionReversarSolicitud
     * @return
     *     returns co.com.rbm.esb.comercio.compra.TipoRespuesta
     */
    @WebMethod
    @WebResult(name = "compraCancelacionReversarRespuesta", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraCancelacionReversarRespuesta")
    public TipoRespuesta compraCancelacionReversar(
        @WebParam(name = "compraCancelacionReversarSolicitud", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", partName = "compraCancelacionReversarSolicitud")
        TipoSolicitudCancelacion compraCancelacionReversarSolicitud);

}
