//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package co.com.rbm.esb.comercio.compra.cancelacion;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import co.com.rbm.esb.comercio.compra.TipoCabeceraSolicitud;
import co.com.rbm.esb.comercio.compra.TipoInfoCompra;
import co.com.rbm.esb.comercio.compra.TipoInfoCompraResp;
import co.com.rbm.esb.comercio.compra.TipoInfoMedioPago;
import co.com.rbm.esb.comercio.compra.TipoInfoMedioPagoIdCuenta;
import co.com.rbm.esb.comercio.compra.TipoRespuesta;
import co.com.rbm.esb.comercio.compra.TipoSolicitudCancelacion;
import co.com.rbm.esb.comercio.compra.TipoSolicitudCompra;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.com.rbm.esb.comercio.compra package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CompraCancelacionProcesarSolicitud_QNAME = new QName("http://www.rbm.com.co/esb/comercio/compra/", "compraCancelacionProcesarSolicitud");
    private final static QName _CompraCancelacionProcesarRespuesta_QNAME = new QName("http://www.rbm.com.co/esb/comercio/compra/", "compraCancelacionProcesarRespuesta");
    private final static QName _CompraCancelacionReversarRespuesta_QNAME = new QName("http://www.rbm.com.co/esb/comercio/compra/", "compraCancelacionReversarRespuesta");
    private final static QName _CompraCancelacionReversarSolicitud_QNAME = new QName("http://www.rbm.com.co/esb/comercio/compra/", "compraCancelacionReversarSolicitud");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.com.rbm.esb.comercio.compra
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TipoSolicitudCancelacion }
     * 
     */
    public TipoSolicitudCancelacion createTipoSolicitudCancelacion() {
        return new TipoSolicitudCancelacion();
    }

    /**
     * Create an instance of {@link TipoRespuesta }
     * 
     */
    public TipoRespuesta createTipoRespuesta() {
        return new TipoRespuesta();
    }

    /**
     * Create an instance of {@link TipoInfoMedioPagoIdCuenta }
     * 
     */
    public TipoInfoMedioPagoIdCuenta createTipoInfoMedioPagoIdCuenta() {
        return new TipoInfoMedioPagoIdCuenta();
    }

    /**
     * Create an instance of {@link TipoInfoCompraResp }
     * 
     */
    public TipoInfoCompraResp createTipoInfoCompraResp() {
        return new TipoInfoCompraResp();
    }

    /**
     * Create an instance of {@link TipoInfoCompra }
     * 
     */
    public TipoInfoCompra createTipoInfoCompra() {
        return new TipoInfoCompra();
    }

    /**
     * Create an instance of {@link TipoSolicitudCompra }
     * 
     */
    public TipoSolicitudCompra createTipoSolicitudCompra() {
        return new TipoSolicitudCompra();
    }

    /**
     * Create an instance of {@link TipoCabeceraSolicitud }
     * 
     */
    public TipoCabeceraSolicitud createTipoCabeceraSolicitud() {
        return new TipoCabeceraSolicitud();
    }

    /**
     * Create an instance of {@link TipoInfoMedioPago }
     * 
     */
    public TipoInfoMedioPago createTipoInfoMedioPago() {
        return new TipoInfoMedioPago();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoSolicitudCancelacion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/comercio/compra/", name = "compraCancelacionProcesarSolicitud")
    public JAXBElement<TipoSolicitudCancelacion> createCompraCancelacionProcesarSolicitud(TipoSolicitudCancelacion value) {
        return new JAXBElement<TipoSolicitudCancelacion>(_CompraCancelacionProcesarSolicitud_QNAME, TipoSolicitudCancelacion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoRespuesta }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/comercio/compra/", name = "compraCancelacionProcesarRespuesta")
    public JAXBElement<TipoRespuesta> createCompraCancelacionProcesarRespuesta(TipoRespuesta value) {
        return new JAXBElement<TipoRespuesta>(_CompraCancelacionProcesarRespuesta_QNAME, TipoRespuesta.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoRespuesta }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/comercio/compra/", name = "compraCancelacionReversarRespuesta")
    public JAXBElement<TipoRespuesta> createCompraCancelacionReversarRespuesta(TipoRespuesta value) {
        return new JAXBElement<TipoRespuesta>(_CompraCancelacionReversarRespuesta_QNAME, TipoRespuesta.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoSolicitudCancelacion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/comercio/compra/", name = "compraCancelacionReversarSolicitud")
    public JAXBElement<TipoSolicitudCancelacion> createCompraCancelacionReversarSolicitud(TipoSolicitudCancelacion value) {
        return new JAXBElement<TipoSolicitudCancelacion>(_CompraCancelacionReversarSolicitud_QNAME, TipoSolicitudCancelacion.class, null, value);
    }

}
