//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.rbm.esb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.com.rbm.esb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.com.rbm.esb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TipoInfoRefCancelacion }
     * 
     */
    public TipoInfoRefCancelacion createTipoInfoRefCancelacion() {
        return new TipoInfoRefCancelacion();
    }

    /**
     * Create an instance of {@link TipoInfoCHIP }
     * 
     */
    public TipoInfoCHIP createTipoInfoCHIP() {
        return new TipoInfoCHIP();
    }

    /**
     * Create an instance of {@link TipoInfoAutenticacion }
     * 
     */
    public TipoInfoAutenticacion createTipoInfoAutenticacion() {
        return new TipoInfoAutenticacion();
    }

    /**
     * Create an instance of {@link TipoIdPersona }
     * 
     */
    public TipoIdPersona createTipoIdPersona() {
        return new TipoIdPersona();
    }

    /**
     * Create an instance of {@link TipoInfoAdicional }
     * 
     */
    public TipoInfoAdicional createTipoInfoAdicional() {
        return new TipoInfoAdicional();
    }

    /**
     * Create an instance of {@link TipoMontoDetallado }
     * 
     */
    public TipoMontoDetallado createTipoMontoDetallado() {
        return new TipoMontoDetallado();
    }

    /**
     * Create an instance of {@link TipoIdTarjetaCredito }
     * 
     */
    public TipoIdTarjetaCredito createTipoIdTarjetaCredito() {
        return new TipoIdTarjetaCredito();
    }

    /**
     * Create an instance of {@link TipoIdTrack }
     * 
     */
    public TipoIdTrack createTipoIdTrack() {
        return new TipoIdTrack();
    }

    /**
     * Create an instance of {@link TipoInfoPago }
     * 
     */
    public TipoInfoPago createTipoInfoPago() {
        return new TipoInfoPago();
    }

    /**
     * Create an instance of {@link TipoIdTarjetaCreditoPrivada }
     * 
     */
    public TipoIdTarjetaCreditoPrivada createTipoIdTarjetaCreditoPrivada() {
        return new TipoIdTarjetaCreditoPrivada();
    }

    /**
     * Create an instance of {@link TipoInfoRespuesta }
     * 
     */
    public TipoInfoRespuesta createTipoInfoRespuesta() {
        return new TipoInfoRespuesta();
    }

    /**
     * Create an instance of {@link TipoInfoImpuestos }
     * 
     */
    public TipoInfoImpuestos createTipoInfoImpuestos() {
        return new TipoInfoImpuestos();
    }

    /**
     * Create an instance of {@link TipoIdTarjetaDebitoPrivada }
     * 
     */
    public TipoIdTarjetaDebitoPrivada createTipoIdTarjetaDebitoPrivada() {
        return new TipoIdTarjetaDebitoPrivada();
    }

    /**
     * Create an instance of {@link TipoIdCuenta }
     * 
     */
    public TipoIdCuenta createTipoIdCuenta() {
        return new TipoIdCuenta();
    }

    /**
     * Create an instance of {@link TipoInfoUbicacion }
     * 
     */
    public TipoInfoUbicacion createTipoInfoUbicacion() {
        return new TipoInfoUbicacion();
    }

}
