//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.rbm.esb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TipoInfoCHIP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoInfoCHIP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codSeguridadEMV" type="{http://www.rbm.com.co/esb/}TipoCodSeguridadEMV"/>
 *         &lt;element name="dataEMV" type="{http://www.rbm.com.co/esb/}TipoDataEMV"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoInfoCHIP", propOrder = {
    "codSeguridadEMV",
    "dataEMV"
})
public class TipoInfoCHIP {

    @XmlElement(required = true)
    protected String codSeguridadEMV;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] dataEMV;

    /**
     * Gets the value of the codSeguridadEMV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodSeguridadEMV() {
        return codSeguridadEMV;
    }

    /**
     * Sets the value of the codSeguridadEMV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodSeguridadEMV(String value) {
        this.codSeguridadEMV = value;
    }

    /**
     * Gets the value of the dataEMV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getDataEMV() {
        return dataEMV;
    }

    /**
     * Sets the value of the dataEMV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataEMV(byte[] value) {
        this.dataEMV = ((byte[]) value);
    }

}
