//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package co.com.rbm.esb.multi.comercio.compra;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "MultiCompraElectronica_HTTP_Service", targetNamespace = "http://www.rbm.com.co/esb/comercio/compra/", wsdlLocation = "META-INF/wsdl/MultiCompraElectronicaService.wsdl")
public class MultiCompraElectronicaHTTPService
    extends Service
{

    private final static URL MULTICOMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException MULTICOMPRAELECTRONICAHTTPSERVICE_EXCEPTION;
    private final static QName MULTICOMPRAELECTRONICAHTTPSERVICE_QNAME = new QName("http://www.rbm.com.co/esb/comercio/compra/", "MultiCompraElectronica_HTTP_Service");

    static {
            MULTICOMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION = co.com.rbm.esb.multi.comercio.compra.MultiCompraElectronicaHTTPService.class.getResource("/META-INF/wsdl/MultiCompraElectronicaService.wsdl");
        WebServiceException e = null;
        if (MULTICOMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/MultiCompraElectronicaService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        MULTICOMPRAELECTRONICAHTTPSERVICE_EXCEPTION = e;
    }

    public MultiCompraElectronicaHTTPService() {
        super(__getWsdlLocation(), MULTICOMPRAELECTRONICAHTTPSERVICE_QNAME);
    }

    public MultiCompraElectronicaHTTPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MULTICOMPRAELECTRONICAHTTPSERVICE_QNAME, features);
    }

    public MultiCompraElectronicaHTTPService(URL wsdlLocation) {
        super(wsdlLocation, MULTICOMPRAELECTRONICAHTTPSERVICE_QNAME);
    }

    public MultiCompraElectronicaHTTPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MULTICOMPRAELECTRONICAHTTPSERVICE_QNAME, features);
    }

    public MultiCompraElectronicaHTTPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultiCompraElectronicaHTTPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MultiCompraElectronicaMsgSetPortType
     */
    @WebEndpoint(name = "MultiCompraElectronica_HTTP_Port")
    public MultiCompraElectronicaMsgSetPortType getMultiCompraElectronicaHTTPPort() {
        return super.getPort(new QName("http://www.rbm.com.co/esb/comercio/compra/", "MultiCompraElectronica_HTTP_Port"), MultiCompraElectronicaMsgSetPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MultiCompraElectronicaMsgSetPortType
     */
    @WebEndpoint(name = "MultiCompraElectronica_HTTP_Port")
    public MultiCompraElectronicaMsgSetPortType getMultiCompraElectronicaHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.rbm.com.co/esb/comercio/compra/", "MultiCompraElectronica_HTTP_Port"), MultiCompraElectronicaMsgSetPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MULTICOMPRAELECTRONICAHTTPSERVICE_EXCEPTION!= null) {
            throw MULTICOMPRAELECTRONICAHTTPSERVICE_EXCEPTION;
        }
        return MULTICOMPRAELECTRONICAHTTPSERVICE_WSDL_LOCATION;
    }

}
