//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package co.com.rbm.esb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.com.rbm.esb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TipoInfoCHIP_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoInfoCHIP");
    private final static QName _TipoIdTarjetaCredito_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoIdTarjetaCredito");
    private final static QName _TipoInfoRespuesta_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoInfoRespuesta");
    private final static QName _TipoInfoPersona_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoInfoPersona");
    private final static QName _TipoIdTrack_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoIdTrack");
    private final static QName _TipoInfoAdicional_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoInfoAdicional");
    private final static QName _TipoInfoImpuestos_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoInfoImpuestos");
    private final static QName _TipoInfoEMV_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoInfoEMV");
    private final static QName _TipoMontoDetallado_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoMontoDetallado");
    private final static QName _TipoInfoUbicacion_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoInfoUbicacion");
    private final static QName _TipoIdTarjetaCreditoPrivada_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoIdTarjetaCreditoPrivada");
    private final static QName _TipoIdPersona_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoIdPersona");
    private final static QName _TipoInfoRefCancelacion_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoInfoRefCancelacion");
    private final static QName _TipoInfoPago_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoInfoPago");
    private final static QName _TipoInfoAutenticacion_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoInfoAutenticacion");
    private final static QName _TipoIdTarjetaDebitoPrivada_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoIdTarjetaDebitoPrivada");
    private final static QName _TipoIdCuenta_QNAME = new QName("http://www.rbm.com.co/esb/", "TipoIdCuenta");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.com.rbm.esb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TipoIdTrack }
     * 
     */
    public TipoIdTrack createTipoIdTrack() {
        return new TipoIdTrack();
    }

    /**
     * Create an instance of {@link TipoInfoPago }
     * 
     */
    public TipoInfoPago createTipoInfoPago() {
        return new TipoInfoPago();
    }

    /**
     * Create an instance of {@link TipoIdTarjetaCreditoPrivada }
     * 
     */
    public TipoIdTarjetaCreditoPrivada createTipoIdTarjetaCreditoPrivada() {
        return new TipoIdTarjetaCreditoPrivada();
    }

    /**
     * Create an instance of {@link TipoInfoRespuesta }
     * 
     */
    public TipoInfoRespuesta createTipoInfoRespuesta() {
        return new TipoInfoRespuesta();
    }

    /**
     * Create an instance of {@link TipoInfoRefCancelacion }
     * 
     */
    public TipoInfoRefCancelacion createTipoInfoRefCancelacion() {
        return new TipoInfoRefCancelacion();
    }

    /**
     * Create an instance of {@link TipoInfoCHIP }
     * 
     */
    public TipoInfoCHIP createTipoInfoCHIP() {
        return new TipoInfoCHIP();
    }

    /**
     * Create an instance of {@link TipoInfoAutenticacion }
     * 
     */
    public TipoInfoAutenticacion createTipoInfoAutenticacion() {
        return new TipoInfoAutenticacion();
    }

    /**
     * Create an instance of {@link TipoInfoImpuestos }
     * 
     */
    public TipoInfoImpuestos createTipoInfoImpuestos() {
        return new TipoInfoImpuestos();
    }

    /**
     * Create an instance of {@link TipoIdTarjetaDebitoPrivada }
     * 
     */
    public TipoIdTarjetaDebitoPrivada createTipoIdTarjetaDebitoPrivada() {
        return new TipoIdTarjetaDebitoPrivada();
    }

    /**
     * Create an instance of {@link TipoIdPersona }
     * 
     */
    public TipoIdPersona createTipoIdPersona() {
        return new TipoIdPersona();
    }

    /**
     * Create an instance of {@link TipoInfoPersona }
     * 
     */
    public TipoInfoPersona createTipoInfoPersona() {
        return new TipoInfoPersona();
    }

    /**
     * Create an instance of {@link TipoIdCuenta }
     * 
     */
    public TipoIdCuenta createTipoIdCuenta() {
        return new TipoIdCuenta();
    }

    /**
     * Create an instance of {@link TipoInfoAdicional }
     * 
     */
    public TipoInfoAdicional createTipoInfoAdicional() {
        return new TipoInfoAdicional();
    }

    /**
     * Create an instance of {@link TipoMontoDetallado }
     * 
     */
    public TipoMontoDetallado createTipoMontoDetallado() {
        return new TipoMontoDetallado();
    }

    /**
     * Create an instance of {@link TipoIdTarjetaCredito }
     * 
     */
    public TipoIdTarjetaCredito createTipoIdTarjetaCredito() {
        return new TipoIdTarjetaCredito();
    }

    /**
     * Create an instance of {@link TipoInfoUbicacion }
     * 
     */
    public TipoInfoUbicacion createTipoInfoUbicacion() {
        return new TipoInfoUbicacion();
    }

    /**
     * Create an instance of {@link TipoInfoEMV }
     * 
     */
    public TipoInfoEMV createTipoInfoEMV() {
        return new TipoInfoEMV();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoInfoCHIP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoInfoCHIP")
    public JAXBElement<TipoInfoCHIP> createTipoInfoCHIP(TipoInfoCHIP value) {
        return new JAXBElement<TipoInfoCHIP>(_TipoInfoCHIP_QNAME, TipoInfoCHIP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoIdTarjetaCredito }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoIdTarjetaCredito")
    public JAXBElement<TipoIdTarjetaCredito> createTipoIdTarjetaCredito(TipoIdTarjetaCredito value) {
        return new JAXBElement<TipoIdTarjetaCredito>(_TipoIdTarjetaCredito_QNAME, TipoIdTarjetaCredito.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoInfoRespuesta }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoInfoRespuesta")
    public JAXBElement<TipoInfoRespuesta> createTipoInfoRespuesta(TipoInfoRespuesta value) {
        return new JAXBElement<TipoInfoRespuesta>(_TipoInfoRespuesta_QNAME, TipoInfoRespuesta.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoInfoPersona }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoInfoPersona")
    public JAXBElement<TipoInfoPersona> createTipoInfoPersona(TipoInfoPersona value) {
        return new JAXBElement<TipoInfoPersona>(_TipoInfoPersona_QNAME, TipoInfoPersona.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoIdTrack }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoIdTrack")
    public JAXBElement<TipoIdTrack> createTipoIdTrack(TipoIdTrack value) {
        return new JAXBElement<TipoIdTrack>(_TipoIdTrack_QNAME, TipoIdTrack.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoInfoAdicional }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoInfoAdicional")
    public JAXBElement<TipoInfoAdicional> createTipoInfoAdicional(TipoInfoAdicional value) {
        return new JAXBElement<TipoInfoAdicional>(_TipoInfoAdicional_QNAME, TipoInfoAdicional.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoInfoImpuestos }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoInfoImpuestos")
    public JAXBElement<TipoInfoImpuestos> createTipoInfoImpuestos(TipoInfoImpuestos value) {
        return new JAXBElement<TipoInfoImpuestos>(_TipoInfoImpuestos_QNAME, TipoInfoImpuestos.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoInfoEMV }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoInfoEMV")
    public JAXBElement<TipoInfoEMV> createTipoInfoEMV(TipoInfoEMV value) {
        return new JAXBElement<TipoInfoEMV>(_TipoInfoEMV_QNAME, TipoInfoEMV.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoMontoDetallado }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoMontoDetallado")
    public JAXBElement<TipoMontoDetallado> createTipoMontoDetallado(TipoMontoDetallado value) {
        return new JAXBElement<TipoMontoDetallado>(_TipoMontoDetallado_QNAME, TipoMontoDetallado.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoInfoUbicacion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoInfoUbicacion")
    public JAXBElement<TipoInfoUbicacion> createTipoInfoUbicacion(TipoInfoUbicacion value) {
        return new JAXBElement<TipoInfoUbicacion>(_TipoInfoUbicacion_QNAME, TipoInfoUbicacion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoIdTarjetaCreditoPrivada }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoIdTarjetaCreditoPrivada")
    public JAXBElement<TipoIdTarjetaCreditoPrivada> createTipoIdTarjetaCreditoPrivada(TipoIdTarjetaCreditoPrivada value) {
        return new JAXBElement<TipoIdTarjetaCreditoPrivada>(_TipoIdTarjetaCreditoPrivada_QNAME, TipoIdTarjetaCreditoPrivada.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoIdPersona }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoIdPersona")
    public JAXBElement<TipoIdPersona> createTipoIdPersona(TipoIdPersona value) {
        return new JAXBElement<TipoIdPersona>(_TipoIdPersona_QNAME, TipoIdPersona.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoInfoRefCancelacion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoInfoRefCancelacion")
    public JAXBElement<TipoInfoRefCancelacion> createTipoInfoRefCancelacion(TipoInfoRefCancelacion value) {
        return new JAXBElement<TipoInfoRefCancelacion>(_TipoInfoRefCancelacion_QNAME, TipoInfoRefCancelacion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoInfoPago }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoInfoPago")
    public JAXBElement<TipoInfoPago> createTipoInfoPago(TipoInfoPago value) {
        return new JAXBElement<TipoInfoPago>(_TipoInfoPago_QNAME, TipoInfoPago.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoInfoAutenticacion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoInfoAutenticacion")
    public JAXBElement<TipoInfoAutenticacion> createTipoInfoAutenticacion(TipoInfoAutenticacion value) {
        return new JAXBElement<TipoInfoAutenticacion>(_TipoInfoAutenticacion_QNAME, TipoInfoAutenticacion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoIdTarjetaDebitoPrivada }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoIdTarjetaDebitoPrivada")
    public JAXBElement<TipoIdTarjetaDebitoPrivada> createTipoIdTarjetaDebitoPrivada(TipoIdTarjetaDebitoPrivada value) {
        return new JAXBElement<TipoIdTarjetaDebitoPrivada>(_TipoIdTarjetaDebitoPrivada_QNAME, TipoIdTarjetaDebitoPrivada.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoIdCuenta }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.rbm.com.co/esb/", name = "TipoIdCuenta")
    public JAXBElement<TipoIdCuenta> createTipoIdCuenta(TipoIdCuenta value) {
        return new JAXBElement<TipoIdCuenta>(_TipoIdCuenta_QNAME, TipoIdCuenta.class, null, value);
    }

}
