//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package co.com.rbm.esb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipoInfoEMV complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipoInfoEMV">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datosToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datosDiscretos" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="estadoToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipoInfoEMV", propOrder = {
    "datosToken",
    "datosDiscretos",
    "estadoToken"
})
public class TipoInfoEMV {

    @XmlElement(required = true)
    protected String datosToken;
    @XmlElement(required = true)
    protected String datosDiscretos;
    @XmlElement(required = true)
    protected String estadoToken;

    /**
     * Gets the value of the datosToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatosToken() {
        return datosToken;
    }

    /**
     * Sets the value of the datosToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatosToken(String value) {
        this.datosToken = value;
    }

    /**
     * Gets the value of the datosDiscretos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatosDiscretos() {
        return datosDiscretos;
    }

    /**
     * Sets the value of the datosDiscretos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatosDiscretos(String value) {
        this.datosDiscretos = value;
    }

    /**
     * Gets the value of the estadoToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoToken() {
        return estadoToken;
    }

    /**
     * Sets the value of the estadoToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoToken(String value) {
        this.estadoToken = value;
    }

}
